<form method="post" action="index.php">
    <fieldset>
        <label for="login">Email:</label>
        <input type="email" id="login" name="login">
    </fieldset>
    <fieldset>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password">
    </fieldset>
    <fieldset>
        <input type="hidden" name="formName" value="formName">
    </fieldset>
    <fieldset>
        <input type="submit" value="Se connecter">
    </fieldset>
</form> 
